security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|build|css|images|js)/
            security: false
        main:
            anonymous: lazy
            switch_user: true
            logout:
                path: app_security_logout
                target: app_default_index
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user/registration, allow_if: "is_anonymous()" }
        - { path: ^/login, allow_if: "is_anonymous()" }
        - { path: ^/recover, allow_if: "is_anonymous()" }
        - { path: ^/, roles: ROLE_USER }
