monolog:
    channels:
        - movieaccess
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!movieaccess"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        access:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_movieaccess.log"
            level: error
            channels: ['movieaccess']
